"""Administrador

Revision ID: 203d0b2e86ab
Revises: 3d9aa95f58d5
Create Date: 2025-12-26 17:36:51.927940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '203d0b2e86ab'
down_revision = '3d9aa95f58d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrador',
    sa.Column('id_persona', sa.UUID(), nullable=False),
    sa.Column('foto', sa.VARCHAR(length=500), nullable=True),
    sa.ForeignKeyConstraint(['id_persona'], ['persona.id_persona'], ),
    sa.PrimaryKeyConstraint('id_persona')
    )
    with op.batch_alter_table('automovil', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_automovil', sa.VARCHAR(length=500), nullable=True))
        batch_op.drop_column('foto')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automovil', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.drop_column('foto_automovil')

    op.drop_table('administrador')
    # ### end Alembic commands ###
