"""baseline

Revision ID: 3d9aa95f58d5
Revises: 
Create Date: 2025-12-25 22:54:35.732782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d9aa95f58d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persona',
    sa.Column('id_persona', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=30), nullable=False),
    sa.Column('apellido_pat', sa.VARCHAR(length=50), nullable=False),
    sa.Column('apellido_mat', sa.VARCHAR(length=50), nullable=False),
    sa.Column('rut', sa.VARCHAR(length=12), nullable=False),
    sa.Column('email', sa.VARCHAR(length=150), nullable=False),
    sa.Column('num_tele', sa.VARCHAR(length=20), nullable=False),
    sa.Column('fecha_nac', sa.DATE(), nullable=False),
    sa.Column('direccion', sa.VARCHAR(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id_persona'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('num_tele'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('conductor',
    sa.Column('id_persona', sa.UUID(), nullable=False),
    sa.Column('licencia', sa.VARCHAR(length=500), nullable=False),
    sa.Column('foto', sa.VARCHAR(length=500), nullable=False),
    sa.Column('hoja_vida_conduct', sa.VARCHAR(length=500), nullable=False),
    sa.Column('anotaciones_internas', sa.VARCHAR(length=2500), nullable=True),
    sa.ForeignKeyConstraint(['id_persona'], ['persona.id_persona'], ),
    sa.PrimaryKeyConstraint('id_persona'),
    sa.UniqueConstraint('licencia')
    )
    op.create_table('propietario',
    sa.Column('id_persona', sa.UUID(), nullable=False),
    sa.Column('foto', sa.VARCHAR(length=500), nullable=True),
    sa.ForeignKeyConstraint(['id_persona'], ['persona.id_persona'], ),
    sa.PrimaryKeyConstraint('id_persona')
    )
    op.create_table('automovil',
    sa.Column('id_automovil', sa.UUID(), nullable=False),
    sa.Column('id_interna', sa.VARCHAR(length=8), nullable=False),
    sa.Column('patente', sa.VARCHAR(length=8), nullable=False),
    sa.Column('id_persona', sa.UUID(), nullable=False),
    sa.Column('vin', sa.VARCHAR(length=25), nullable=False),
    sa.Column('marca', sa.VARCHAR(length=30), nullable=False),
    sa.Column('modelo', sa.VARCHAR(length=30), nullable=False),
    sa.Column('tipo_vehiculo', sa.VARCHAR(length=30), nullable=False),
    sa.Column('anio', sa.INTEGER(), nullable=False),
    sa.Column('color', sa.VARCHAR(length=20), nullable=False),
    sa.Column('foto', sa.VARCHAR(length=500), nullable=True),
    sa.ForeignKeyConstraint(['id_persona'], ['propietario.id_persona'], ),
    sa.PrimaryKeyConstraint('id_automovil'),
    sa.UniqueConstraint('id_interna'),
    sa.UniqueConstraint('patente'),
    sa.UniqueConstraint('vin')
    )
    op.create_table('venta_guia',
    sa.Column('id_guia', sa.UUID(), nullable=False),
    sa.Column('id_interna_desde', sa.INTEGER(), nullable=False),
    sa.Column('id_interna_hasta', sa.INTEGER(), nullable=False),
    sa.Column('valor_guia', sa.INTEGER(), nullable=False),
    sa.Column('cantidad_guias', sa.INTEGER(), nullable=False),
    sa.Column('total_venta', sa.INTEGER(), nullable=False),
    sa.Column('fecha_venta', sa.TIMESTAMP(), nullable=False),
    sa.Column('id_persona', sa.UUID(), nullable=False),
    sa.Column('monto', sa.FLOAT(), nullable=False),
    sa.Column('guia_venta', sa.VARCHAR(length=500), nullable=False),
    sa.ForeignKeyConstraint(['id_persona'], ['propietario.id_persona'], ),
    sa.PrimaryKeyConstraint('id_guia')
    )
    op.create_table('documento',
    sa.Column('id_documento', sa.UUID(), nullable=False),
    sa.Column('id_automovil', sa.UUID(), nullable=False),
    sa.Column('padron', sa.VARCHAR(length=500), nullable=False),
    sa.Column('seguro_obligatorio', sa.VARCHAR(length=500), nullable=False),
    sa.Column('revision_tec', sa.VARCHAR(length=500), nullable=False),
    sa.Column('seguro_complementario', sa.VARCHAR(length=500), nullable=True),
    sa.Column('permiso_circulacion', sa.VARCHAR(length=500), nullable=False),
    sa.Column('cav', sa.VARCHAR(length=500), nullable=False),
    sa.Column('cartola_recorrido', sa.VARCHAR(length=500), nullable=False),
    sa.Column('fecha_vencimiento', sa.DATE(), nullable=False),
    sa.Column('estado', sa.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_automovil'], ['automovil.id_automovil'], ),
    sa.PrimaryKeyConstraint('id_documento')
    )
    op.create_table('turno',
    sa.Column('id_turno', sa.UUID(), nullable=False),
    sa.Column('id_automovil', sa.UUID(), nullable=False),
    sa.Column('id_persona', sa.UUID(), nullable=False),
    sa.Column('fecha_ini', sa.TIMESTAMP(), nullable=False),
    sa.Column('fecha_fin', sa.TIMESTAMP(), nullable=False),
    sa.Column('estado', sa.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_automovil'], ['automovil.id_automovil'], ),
    sa.ForeignKeyConstraint(['id_persona'], ['conductor.id_persona'], ),
    sa.PrimaryKeyConstraint('id_turno')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turno')
    op.drop_table('documento')
    op.drop_table('venta_guia')
    op.drop_table('automovil')
    op.drop_table('propietario')
    op.drop_table('conductor')
    op.drop_table('persona')
    # ### end Alembic commands ###
