"""update_schema

Revision ID: 63961609dec2
Revises: 6aa5021d697c
Create Date: 2025-12-26 20:26:36.919415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63961609dec2'
down_revision = '6aa5021d697c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('administrador', schema=None) as batch_op:
        batch_op.drop_column('foto')

    with op.batch_alter_table('conductor', schema=None) as batch_op:
        batch_op.drop_column('foto')

    with op.batch_alter_table('master_admin', schema=None) as batch_op:
        batch_op.drop_column('foto')

    with op.batch_alter_table('persona', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto', sa.String(length=500), nullable=False))

    with op.batch_alter_table('persona_rol', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_perosnarol', sa.UUID(), nullable=False))

    with op.batch_alter_table('propietario', schema=None) as batch_op:
        batch_op.drop_column('foto')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('propietario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto', sa.VARCHAR(length=500), autoincrement=False, nullable=True))

    with op.batch_alter_table('persona_rol', schema=None) as batch_op:
        batch_op.drop_column('id_perosnarol')

    with op.batch_alter_table('persona', schema=None) as batch_op:
        batch_op.drop_column('foto')

    with op.batch_alter_table('master_admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto', sa.VARCHAR(length=500), autoincrement=False, nullable=True))

    with op.batch_alter_table('conductor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto', sa.VARCHAR(length=500), autoincrement=False, nullable=False))

    with op.batch_alter_table('administrador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto', sa.VARCHAR(length=500), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
