"""update_schema

Revision ID: 6aa5021d697c
Revises: d76f160f679b
Create Date: 2025-12-26 18:44:28.876574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6aa5021d697c'
down_revision = 'd76f160f679b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rol',
    sa.Column('id_rol', sa.UUID(), nullable=False),
    sa.Column('nombre_rol', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('nombre_rol')
    )
    op.create_table('persona_rol',
    sa.Column('id_persona', sa.UUID(), nullable=False),
    sa.Column('id_rol', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id_persona'], ['persona.id_persona'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_rol'], ['rol.id_rol'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_persona', 'id_rol')
    )
    with op.batch_alter_table('administrador', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('administrador_id_persona_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'persona', ['id_persona'], ['id_persona'], ondelete='CASCADE')

    with op.batch_alter_table('conductor', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('conductor_id_persona_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'persona', ['id_persona'], ['id_persona'], ondelete='CASCADE')

    with op.batch_alter_table('master_admin', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('master_admin_id_persona_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'persona', ['id_persona'], ['id_persona'], ondelete='CASCADE')

    with op.batch_alter_table('propietario', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('propietario_id_persona_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'persona', ['id_persona'], ['id_persona'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('propietario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('propietario_id_persona_fkey'), 'persona', ['id_persona'], ['id_persona'])

    with op.batch_alter_table('master_admin', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('master_admin_id_persona_fkey'), 'persona', ['id_persona'], ['id_persona'])

    with op.batch_alter_table('conductor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('conductor_id_persona_fkey'), 'persona', ['id_persona'], ['id_persona'])

    with op.batch_alter_table('administrador', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('administrador_id_persona_fkey'), 'persona', ['id_persona'], ['id_persona'])

    op.drop_table('persona_rol')
    op.drop_table('rol')
    # ### end Alembic commands ###
