"""add nuevas tablas y columnas

Revision ID: 83ed6b7de2e7
Revises: 63961609dec2
Create Date: 2025-12-27 19:57:06.845684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83ed6b7de2e7'
down_revision = '63961609dec2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pais',
    sa.Column('id_pais', sa.UUID(), nullable=False),
    sa.Column('nombre_pais', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_pais'),
    sa.UniqueConstraint('nombre_pais')
    )
    op.create_table('ciudad',
    sa.Column('id_ciudad', sa.UUID(), nullable=False),
    sa.Column('nombre_ciudad', sa.String(length=100), nullable=False),
    sa.Column('id_pais', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id_pais'], ['pais.id_pais'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_ciudad'),
    sa.UniqueConstraint('nombre_ciudad')
    )
    with op.batch_alter_table('persona', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_pais', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('id_ciudad', sa.UUID(), nullable=False))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.create_foreign_key(None, 'ciudad', ['id_ciudad'], ['id_ciudad'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'pais', ['id_pais'], ['id_pais'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persona', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('id_ciudad')
        batch_op.drop_column('id_pais')

    op.drop_table('ciudad')
    op.drop_table('pais')
    # ### end Alembic commands ###
