"""add reset_once a Persona

Revision ID: adbd58f4b3d3
Revises: 83ed6b7de2e7
Create Date: 2025-12-28 17:38:59.321107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adbd58f4b3d3'
down_revision = '83ed6b7de2e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ciudad', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_ciudad_id_pais'))

    with op.batch_alter_table('persona', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_nonce', sa.UUID(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persona', schema=None) as batch_op:
        batch_op.drop_column('reset_nonce')

    with op.batch_alter_table('ciudad', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_ciudad_id_pais'), ['id_pais'], unique=False)

    # ### end Alembic commands ###
