"""Master_admin

Revision ID: d76f160f679b
Revises: 203d0b2e86ab
Create Date: 2025-12-26 17:46:53.815209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd76f160f679b'
down_revision = '203d0b2e86ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_admin',
    sa.Column('id_persona', sa.UUID(), nullable=False),
    sa.Column('foto', sa.VARCHAR(length=500), nullable=True),
    sa.ForeignKeyConstraint(['id_persona'], ['persona.id_persona'], ),
    sa.PrimaryKeyConstraint('id_persona')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('master_admin')
    # ### end Alembic commands ###
